### ISSUE TITLE
Can't compile windows project after install react-native-slider

### ISSUE THREAD

**Issue by Deftwun** [callstack/react-native-slider#314] opened 2021-09-09 12:23 UTC
## Description

Can't build & launch simple react-native windows app after installing `react-native-slider`

The windows project will fail to build with this error
`midl: Assertion failed: node == nullptr, file com\rpc\midl\midlrt\metaread\metadataparser.cxx, line 216`

I've also duplicated this same issue with [react-native-screens](https://github.com/software-mansion/react-native-screens/issues) so it's possible that something is broken in my environment or I'm doing something dumb.

## Reproducible Demo

- `npx react-native init AwesomeProject`
- `cd AwesomeProject`
- `npx react-native-windows-init --overwrite`
- `npx react-native run-windows` will launch a working uwp app
- `npm install @react-native-community/slider --save`
- `npx react-native run-windows` will now fail with below output

```
warn Package react-native-windows has been ignored because it contains invalid configuration. Reason: Cannot find module '@react-native-community/cli/package.json'
```

- `npm install --save-dev @react-native-community/cli` fixes that but not sure that's right approach
- `npx react-native run-windows` will now fail with below output

```
$ npx react-native run-windows
 ✔ Auto-linking...
Success: No auto-linking changes necessary. (331ms)
 ✔ Found compatible MSBuild at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin (16.11.31624.102)
 ✔ Found Solution: C:\dev\AwesomeProject\windows\awesomeproject.sln
 ℹ Build configuration: Debug
 ℹ Build platform: x86
 ✖ Building Solution: midl: Assertion failed: node == nullptr, file com\rpc\midl\midlrt\metaread\metadataparser.c...
 ✖ Build failed with message Building Solution - error code 1. Check your build configuration.
Re-run the command with --logging for more information
Your session id was acd1970b2360ed52ba015b0e4820e436
```

## Environment

```
$ npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 10.53 GB / 15.86 GB
  Binaries:
    Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1, 30.0.2
      System Images: android-26 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.15063.0, 10.0.16299.0, 10.0.17134.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.31624.102 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_302 - C:\Program Files\OpenJDK\openjdk-8u302-b08\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: ^5.0.1 => 5.0.1
    react: 17.0.2 => 17.0.2
    react-native: 0.65.1 => 0.65.1
    react-native-windows: 0.65.2 => 0.65.2
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by BartoszKlonowski** [comment] 2021-09-09 14:52
Hello @Deftwun!
I couldn't reproduce your issue by following your steps, on my side the app build and works well.
The *Slider* package does not have the *@react-native-community/cli* as a dependency, so I don't see that would be an issue.
Also I don't think that this is related to the *Slider* itself, as the compilation doesn't mention it directly.

Would it be possible for you to provide this issue with build logs taken with `--logging` flag?
You can paste it to any text file and put as an attachment here.

**Comment by Deftwun** [comment] 2021-09-09 18:21
@BartoszKlonowski Thanks I'm afraid it might be an environment or windows permission issue maybe? I noticed some warnings after installing slider so I attached my terminal output from my example as well. 

[git-bash-slider-example.txt](https://github.com/callstack/react-native-slider/files/7138897/git-bash-slider-example.txt)
[slider-run-with-logging.txt](https://github.com/callstack/react-native-slider/files/7138898/slider-run-with-logging.txt)

**Comment by BartoszKlonowski** [comment] 2021-09-09 20:11
Thank you, @Deftwun,
I can see that you are using the latest MSBuild, so I also upgraded to the *16.11.3164*, but still couldn't reproduce it.
Moreover the fact that the same issue happens for you when using *react-native-screens* tells me that most probably this is an issue with your Visual Studio installation.
The quickest solution for `MIDL8009` error I can suggest is to reinstall your Visual Studio and install all [RNW requirements](  https://microsoft.github.io/react-native-windows/docs/rnw-dependencies#install-the-development-dependencies).

---

There are however two things that l find suspicious in your environment:
* Versions: 10.0.15063.0, 10.0.17134.0, 10.0.17763.0  are already outdated (especially *10.0.15063.0*!) and can be uninstalled.
I tried the build with 10.0.17 and there's still no issue, but I will download the 10.0.15063 later today and check if this is the one causing conflicts and issues.
* You are manually installing *@react-native-community/cli* to get the `run-windows` after installing `react-native-windows`.

**Comment by BartoszKlonowski** [comment] 2021-09-10 11:19
@Deftwun I couldn't reproduce your issue even with the 10.0.15063 installed.
I will stick to my first suggestion to just make a full reinstall of whole Visual Studio along with Windows SDK (they should be reinstalled automatically when reinstalling VS).
I will need to close this issue as it is not related directly to this library.

**Closed by BartoszKlonowski** 2021-09-10 11:19 UTC
Labels: bug report, platform: Windows
