### ISSUE TITLE
Error when adding children elements inside of the Slider component

### ISSUE THREAD

**Issue by amcneel** [callstack/react-native-slider#457] opened 2022-11-29 20:10 UTC
## Environment

`System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 114.08 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`

## Description

On iOS I'm able to add child elements inside of `<Slider> ... </Slider>` but this errors on Android

## Reproducible Demo

Add a View inside the element and run on both iOS and Android

**Comment by BartoszKlonowski** [comment] 2023-06-30 11:59
Let me close this as a duplicate of #512.
Please track the progress in the original issue, thank you!

**Closed by BartoszKlonowski** 2023-06-30 11:59 UTC
Labels: bug report, duplicate, platform: Android
