### ISSUE TITLE
'java.util.ArrayList android.animation.AnimatorSet$Node.nodeDependents' on a null object reference

### ISSUE THREAD

**Issue by BennyTian** [callstack/react-native-slider#357] opened 2022-02-15 07:05 UTC
## Environment

Happens on several operating systems. All running inside electron:

### react-native env:
"react-native": "0.61.5",
"@react-native-community/slider": "^4.2.0"

### android env:
minSdkVersion = 17
buildToolsVersion = "28.0.3"
compileSdkVersion = 28
targetSdkVersion = 28
supportLibVersion = 28
kotlin_version = '1.3.72'

### bug devices:
Android 6.0,level 23
Android 6.0.1,level 23

## Description

An error occurs in the production environment:

`
Attempt to write to field 'java.util.ArrayList android.animation.AnimatorSet$Node.nodeDependents' on a null object reference
com.reactnativecommunity.slider.ReactSlider.<init>(ReactSlider.java:71)
`

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/3095848/154009908-f968e65c-811e-4317-b1d7-f06db91f54cb.png">

**Comment by BartoszKlonowski** [comment] 2022-02-15 10:54
Hello @BennyTian,
would it be possible for you to fill the description with the reproducible demo?

**Comment by BartoszKlonowski** [comment] 2022-11-22 22:15
Closing due to lack of author's response, outdated versions of Slider and react-native.
Feel free to reach out when issue is noticed again.

**Closed by BartoszKlonowski** 2022-11-22 22:15 UTC
Labels: bug report, platform: Android, requires: author feedback
