### ISSUE TITLE
Android Type com.reactnativecommunity.slider.BuildConfig is defined multiple times

### ISSUE THREAD

**Issue by AndrewLutsenko** [callstack/react-native-slider#506] opened 2023-04-17 18:17 UTC
## Environment

System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12600K
    Memory: 18.78 GB / 31.75 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-221.6008.13.2211.9619390
    Visual Studio: Not Found
  Languages:
    Java: 11.0.17 - /c/Program Files/OpenJDK/jdk-11.0.17.8-hotspot/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Description

If i install package
yarn add @react-native-comunity/slider i always get an error

I have already try this way 
 implementation(project(':react-native-jitsi-meet')) {
        exclude group: 'com.facebook.react', module: 'react-native-svg'
        exclude group: 'com.facebook.react', module: 'react-native-reanimated'
        exclude group: 'com.facebook.react', module: 'react-native-device-info'
        exclude group: 'com.facebook.react', module: 'react-native-gesture-handler'
        exclude group: 'com.facebook.react', module: 'react-native-video'
        exclude group: 'com.facebook.react', module: 'react-native-safe-area-context'
        exclude group: 'com.facebook.react', module: 'react-native-screens'
        exclude group: 'com.facebook.react', module: 'react-native-google-signin'
        exclude group: 'com.facebook.react', module: 'react-native-community_slider'
   }

Type com.reactnativecommunity.slider.BuildConfig is defined multiple times

## Reproducible Demo

![image](https://user-images.githubusercontent.com/129854280/232573513-1a515b89-018f-4879-9a05-ea8b286cb0ff.png)

**Comment by AndrewLutsenko** [comment] 2023-04-18 14:19
Its work for IOS
Android still have trouble
 @BartoszKlonowski could u help plz?

**Comment by itallianez** [comment] 2023-04-18 14:21
React-Native 0.70.1

Have the same error

**Comment by antonKutakov** [comment] 2023-04-18 14:29
I have react-native 0.70.6 too
When i try to install 

"@react-native-community/clipboard": "^1.5.1",
"@react-native-community/geolocation": "^3.0.5",
"@react-native-community/slider": "^4.3.3",

I have error multyDex, any solutions?

**Comment by BartoszKlonowski** [comment] 2023-04-18 14:48
@AndrewLutsenko @itallianez @antonKutakov Can you folks share your `package.json` files? At least the deps you have installed? I must say I never encountered such error, but I'll try to investigate once you provide me with more info.

**Comment by AndrewLutsenko** [comment] 2023-04-23 15:46
@BartoszKlonowski hello guys do u have any news?

**Comment by BartoszKlonowski** [comment] 2023-06-16 13:44
Dears, @AndrewLutsenko @antonKutakov @itallianez,
I was not able to reproduce the error you mention.
I will require some ready reproduction repository to clone it and work on it. Can you provide me with one?

**Comment by BartoszKlonowski** [comment] 2023-06-30 11:46
@AndrewLutsenko @antonKutakov @itallianez Just a reminder to provide me with a full repro repository that I can clone and check the issue, thanks!

**Comment by BartoszKlonowski** [comment] 2023-07-07 11:53
Closing due to no reproduction repository.
Also as a note: most probably it's one of the dependencies installed that is causing this, but I was unable to verify which exactly (if).
In case of more users noticing this please notify me and share a link to repo that I clone to observe and analyse this.
Thank you!

**Closed by BartoszKlonowski** 2023-07-07 11:53 UTC
Labels: bug report, platform: Android, requires: author feedback
