### ISSUE TITLE
Sliding back to old position

### ISSUE THREAD

**Issue by Vednus** [callstack/react-native-slider#213] opened 2020-07-21 16:17 UTC
Is anyone else having it slide back to its previous position after sliding it to a position? It only happens randomly at a few positions on the slider. Started happening on 3.0.2 and continued into 3.0.3. Happening on ios simulator and real device.

I tried changing the step and commenting out `onValueChange` and `onSlidingComplete`, but neither worked.

**Comment by superplussed** [comment] 2020-07-24 09:15
I am having this problem as well. :/

**Comment by AmirDoreh** [comment] 2020-07-25 14:13
i had also the same problem , which i solved it by passing the props directly not through an state manager or storing it to the state!

**Comment by Vednus** [comment] 2020-07-27 23:22
I've removed all props and it's still happening. I've also memoed the containing component to make sure it's not rerendering and it's still happening. Not sure if it's also related to upgrading to rn 63.1

**Comment by JoelOnGithub** [comment] 2020-08-06 12:59
We have the same issue. Happens only on iOS 13.6.x, 13.5.x is fine. Downgrading to react-native-slider to the latest version 2 solves it though.

**Comment by jenskuhrjorgensen** [comment] 2020-08-17 12:47
Thanks @JoelOnGithub - I downgraded to latest version 2 (2.0.9 at the moment) and it seems to have solved it. 👍

**Comment by bimalgrg519** [comment] 2020-08-29 13:04
Downgrading to version 2.0.9 worked for me as well.

**Comment by R4DIC4L** [comment] 2021-02-01 16:42
I noticed this only happens on android, on ios it seems to be working fine. I am using version 3.0.3.

I found an ugly workaround (hack) to send the modified value only as initial value on mount, as it seems that changing the `value` prop on android messes with the rendering when using the value in controlled mode (e.g.: in a form with redux-form or formik that saved the state value and sends it to the component) in react-native, while Slider knows how to properly display the slider thumb internally after change:

```typescript
import Slider, { SliderProps } from '@react-native-community/slider';

class CustomSlider extends React.Component<SliderProps> {
  private _startValue?: number = undefined;

  componentDidMount() {
    this._startValue = this.props?.value;
  }

  getSliderValue = (value?: number) => {
    return Platform.OS === 'android' ? this._startValue : value;
  }

  render() {
    const { value, ...sliderProps } = this.props;

    const sliderValue = this.getSliderValue(value);

    return (
      <Slider
        value={sliderValue}
        {...sliderProps}
      />
    );
  }
}

export default CustomSlider;

```

Seems onValueChange and onSlidingComplete themselves work fine, they report when user changes the value (I also use a text component next to the slider to check the value), it is just the rendering with value prop interference.

**Comment by dukoo** [comment] 2021-03-17 13:18
I have the same issue on iOS even when no handler is set - just raw Slider component. In my case the problem occurs when I slowly move slider towards 0 and release it with value about 10-15%, then it bounces to some value between old position and the new one.

**Comment by dukoo** [comment] 2021-03-17 13:30
I see that the issue is already solved and waits to be published: https://github.com/callstack/react-native-slider/pull/235

**Comment by BartoszKlonowski** [comment] 2021-08-23 19:12
Hello @Vednus! The latest version v4.1.1 has been released and it contains the fix mentioned by @dukoo (thank you!).
I will close this issue with this PR linked, but feel free to reopen if this does not fix your case.

**Closed by BartoszKlonowski** 2021-08-23 19:12 UTC
Labels: bug report

**Comment by Vednus** [comment] 2021-08-23 20:13
Sweet! Thank you. I'll upgrade from v2
