### ISSUE TITLE
README React Native Compatibility table needs to be updated

### ISSUE THREAD

**Issue by Knufle** [callstack/react-native-slider#414] opened 2022-08-10 09:38 UTC
## Environment

System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Memory: 1.67 GB / 15.94 GB
  Binaries:
    Node: 14.19.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: Not Found
  Languages:
    Java: 17.0.3 - C:\Program Files\Java\jdk-17.0.3\bin\javac.EXE
    Python: 3.10.4 - C:\Python310\python.EXE
  npmPackages:
    @react-native-community/cli: ^4.14.0 => 4.14.0
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Description

I just wanted to let you guys know that I think the README React Native Compatibility table needs to be updated, I tried installing with `npm install @react-native-community/slider --save` yesterday and was getting this error after running `react-native run-android --appIdSuffix local`: 

![image](https://user-images.githubusercontent.com/25941471/183868775-5c839558-a0d2-462b-9c35-641c18420861.png)

which I think was introduced in 4.3.0? Anyways, I downgraded to 4.2.4, and apparently, it's working now, I guess the fix should look something like this. But I'm not 100% sure about Windows and if it's only >= 0.69 so...

## React Native Compatibility
To use this library you need to ensure you are using the correct version of React Native.

| `@react-native-community/slider` version | Required React Native Version |
| ---------------------------------------- | ----------------------------- |
| `4.3.x`                                  | `>=0.69`                      |
| `4.2.x`                                  | `>=0.60`; `>=0.62` (on Windows);  |
| `3.1.x`                                  | `>=0.60`                      |
| `2.x.x`                                  | `>= 0.60`                     |
| [`1.x.x`](https://github.com/react-native-community/react-native-slider/tree/937f0942f1fffc6ed88b5cf7c88d73b7878f00f0)  | `<= 0.59` |

**Comment by BartoszKlonowski** [comment] 2022-08-10 14:46
Thank you for reporting, @Knufle!
I will take a look into that

**Comment by mbastian93** [comment] 2022-08-12 09:18
I had the same issue;

I followed [this](https://github.com/facebook/react-native/issues/33067#issuecomment-1103189677) and it seems to work as expected (as far as i can tell).

**Comment by BartoszKlonowski** [comment] 2022-08-12 22:07
@Knufle After some investigation I found out that the problem is with the dependencies taken for new arch build when having older RN versions.
I'm working on the fix, but the idea is to avoid the compatibility issues - I don't want to have the latest 4.3.0 version be only for the latest RN versions, but I want to keep the backward compatibility instead.
That is why I decided not to update the compatibility table, but fix the Android build issue instead.
I will close this item as invalid, but please track the fix progress in #415.
I will also post here once the hotfix is released.
Thank you!

**Closed by BartoszKlonowski** 2022-08-12 22:07 UTC
Labels: bug report, invalid, dependencies, documentation

**Comment by Knufle** [comment] 2022-08-13 14:21
@BartoszKlonowski You're welcome! Your proposed solution sounds very good, I'm glad to be making a teeny-tiny contribution to this amazing project :)

**Comment by minhas-weoveri** [comment] 2022-08-17 09:06
I am facing the same issue.

**Comment by BartoszKlonowski** [comment] 2022-08-20 11:50
@Knufle The fix is now released in v4.3.1
