### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNCSlider" was not found in the UIManager.

### ISSUE THREAD

**Issue by bj97301** [callstack/react-native-slider#509] opened 2023-05-15 23:34 UTC
## Environment
expo dev ios:
```json

"dependencies": {
    "@react-native-community/slider": "^4.4.2",
    "buffer": "^6.0.3",
    "expo": "~48.0.9",
    "expo-application": "~5.1.1",
    "expo-constants": "~14.2.1",
    "expo-device": "~5.2.1",
    "expo-location": "~15.1.1",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "expo-system-ui": "^2.2.1",
    "expo-updates": "~0.16.4",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-native": "0.71.7",
    "react-native-event-listeners": "^1.0.7",
    "react-native-slider": "^0.11.0",
    "react-native-toast-message": "^2.1.6",
    "react-redux": "^8.0.5",
    "sentry-expo": "~6.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@testing-library/jest-native": "^5.4.2",
    "@testing-library/react-native": "^12.0.1",
    "@types/jest": "^29.5.0",
    "@types/node": "^18.15.11",
    "@typescript-eslint/eslint-plugin": "^5.57.0",
    "eslint": "^8.37.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-config-react-app": "^7.0.1",
    "eslint-config-standard-with-typescript": "^34.0.1",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-n": "^15.7.0",
    "eslint-plugin-prefer-arrow": "^1.2.3",
    "eslint-plugin-prefer-let": "^3.0.1",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-react-native": "^4.0.0",
    "expo-dev-client": "~2.2.1",
    "expo-permissions": "^14.1.1",
    "jest": "^29.2.1",
    "jest-cli": "^29.5.0",
    "jest-expo": "^48.0.2",
    "prettier": "^2.8.7",
    "prettier-plugin-tailwindcss": "^0.2.8",
    "tailwindcss": "^3.3.2",
    "typescript": "^4.9.4"
  },

```

* react-native info output:
```bash
 ERROR  Invariant Violation: requireNativeComponent: "RNCSlider" was not found in the UIManager.

This error is located at:
    in RNCSlider (at Slider.tsx:248)
    in SliderComponent (created by SettingsController)
    in RCTView (created by View)
    in View
    in NativeWind.View
    in Unknown (created by SettingsController)
    in RCTScrollContentView (created by ScrollView)
    in RCTScrollView (created by ScrollView)
    in ScrollView (created by ScrollView)
    in ScrollView (created by SettingsController)
    in RCTSafeAreaView
    in Styled
    in Unknown (created by SettingsController)
    in SettingsController (created by App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer (created by Modal)
    in RCTView (created by View)
    in View (created by Modal)
    in VirtualizedListContextResetter (created by Modal)
    in RCTModalHostView (created by Modal)
    in Modal (created by App)
    in RCTSafeAreaView (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
 ERROR  Invariant Violation: requireNativeComponent: "RNCSlider" was not found in the UIManager.

This error is located at:
    in RNCSlider (at Slider.tsx:248)
    in SliderComponent (created by SettingsController)
    in RCTView (created by View)
    in View
    in NativeWind.View
    in Unknown (created by SettingsController)
    in RCTScrollContentView (created by ScrollView)
    in RCTScrollView (created by ScrollView)
    in ScrollView (created by ScrollView)
    in ScrollView (created by SettingsController)
    in RCTSafeAreaView
    in Styled
    in Unknown (created by SettingsController)
    in SettingsController (created by App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer (created by Modal)
    in RCTView (created by View)
    in View (created by Modal)
    in VirtualizedListContextResetter (created by Modal)
    in RCTModalHostView (created by Modal)
    in Modal (created by App)
    in RCTSafeAreaView (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes

```

* are you using the new architecture?
yes?
* which version of react & react-native are you using?
    "react-native": "0.71.7",

## Description

I get the above error when I try to return this:
```js

<Slider
  style={{width: 200, height: 40}}
  minimumValue={0}
  maximumValue={1}
  minimumTrackTintColor="#FFFFFF"
  maximumTrackTintColor="#000000"
/> 

```

**Comment by BartoszKlonowski** [comment] 2023-05-16 01:09
Hello @bj97301, thanks for reaching out!
Judging by the [comment of yours](https://github.com/callstack/react-native-slider/issues/330#issuecomment-1548747837) we can agree to close this as a duplicate of #330.
Please track the progress in the original issue, thank you!

**Closed by BartoszKlonowski** 2023-05-16 01:09 UTC
Labels: bug report, duplicate
