### ISSUE TITLE
Android Build Failed - Could not resolve all artifacts for configuration ':react-native-community_slider:classpath'. 

### ISSUE THREAD

**Issue by Md-Mudassir47** [callstack/react-native-slider#415] opened 2022-08-11 10:29 UTC
It was running fine till yesterday, I had not updated the package & once it started to throw this issue I then upgraded to the latest version but still the same issue

### Version Details
```
"@react-native-community/slider": "^4.2.0",
"react-native-slider": "^0.11.0",
"react-native": "^0.67.4",
```

### Current Version Of Slider
`"@react-native-community/slider": "^4.3.0",`

```
* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all dependencies for configuration ':app:debugCompileClasspath'.
   > A problem occurred configuring project ':react-native-community_slider'.
      > Could not resolve all artifacts for configuration ':react-native-community_slider:classpath'.
         > Could not find com.facebook.react:react-native-gradle-plugin:.
           Required by:
               project :react-native-community_slider
```

**Comment by Mateoooo** [comment] 2022-08-11 10:49
I have the same problem. 
`"react-native": "^0.67.2",
`

**Comment by valery-lavrik** [comment] 2022-08-11 10:55
I have the same problem.
`"react-native": "0.66.4",`

**Comment by BartoszKlonowski** [comment] 2022-08-11 11:17
@Md-Mudassir47 Are you able to share all the details about:
* react-native version you are using
* Slider version you were using before this error appeared
* Slider version you are using now

This is a duplicate of already reported issue (all have the same root cause): #414 #416,
I'm aware of this problem and I'm actively working on this.

**Comment by Md-Mudassir47** [comment] 2022-08-11 11:21
> @Md-Mudassir47 Are you able to share all the details about:
> 
> * react-native version you are using
> * Slider version you were using before this error appeared
> * Slider version you are using now
> 
> This is a duplicate of already reported issue (all have the same root cause): #414 #416, I'm aware of this problem and I'm actively working on this.

I've updated it

**Comment by Md-Mudassir47** [comment] 2022-08-11 11:23
@BartoszKlonowski I managed to fix it by 
Removing `@react-native-community/slider": "^4.2.0`
Replace `import Slider from '@react-native-community/slider';` -> `import Slider from 'react-native-slider';`

**Comment by BartoszKlonowski** [comment] 2022-08-11 11:29
> @BartoszKlonowski I managed to fix it by Removing `@react-native-community/slider": "^4.2.0` Replace `import Slider from '@react-native-community/slider';` -> `import Slider from 'react-native-slider';`
> 
> Works on both iOS & Android, Android Build is successful 🎉

This is not a fix, this is just using another package, but I'm glad you have your app unblocked 👍

**Comment by luizgallas** [comment] 2022-08-16 02:25
I am facing the same issue, any solution?

**Comment by minhas-weoveri** [comment] 2022-08-17 09:09
I am facing the same issue.

**Comment by dipankurXT** [comment] 2022-08-17 12:44
Same issue here

**Comment by MrQureshi** [comment] 2022-08-17 15:50
"^4.3.0" this version is unstable for now downgrade version with "4.2.0" and remove caret symbol 
 
 then run command  `npx jetify`

**problem solved**

**Closed** 2022-08-17 19:26 UTC
Labels: bug report, platform: Android, new architecture

**Comment by one-god** [comment] 2022-08-18 01:44
I am facing the same issue.

**Comment by valery-lavrik** [comment] 2022-08-18 05:09
Yes, just fix the slider connection in the **package.json**

`"@react-native-community/slider": "4.2.4",`

A little higher has already been answered

**Comment by BartoszKlonowski** [comment] 2022-08-20 11:50
The fix is now released in v4.3.1

**Comment by NguyenPhuongNam99** [comment] 2022-10-13 03:28
please install version 4.2.4 . It is fix me!

**Comment by AndrewLutsenko** [comment] 2023-04-17 18:06
![image](https://user-images.githubusercontent.com/129854280/232572335-cbdcd4aa-8d5b-4e90-bd73-e233569adfae.png)
Still not work

react-native v0.70.6
"@react-native-community/slider": "4.3.1",

**Comment by ansarikhurshid786** [comment] 2024-09-11 08:53
4.3.1 works for react native 0.64.4
