### ISSUE TITLE
How to set track's style?

### ISSUE THREAD

**Issue by davidguo1** [callstack/react-native-slider#197] opened 2020-06-24 08:06 UTC
Is there a way to set the track style? I want to change the track's height, I mean the height of the track line, not the whole component height.

**Comment by rectified95** [comment] 2020-07-13 23:56
You'd need to defer to native platforms' docs. If they support it, then it can be exposed on the JS side and fed down to the native.

**Comment by achord** [comment] 2020-07-24 02:56
Can we get a feature request?

**Comment by Sharcoux** [comment] 2020-08-01 22:30
You can try @sharcoux/slider
If you have issues with the version 4.0.0 which is brand new, you can try the 3.3.1 which is probably more reliable for now.
It is basically the web implementation of this slider but made compatible with Android and iOS.

**Comment by raazatul7** [comment] 2020-09-01 07:06
> Is there a way to set the track style? I want to change the track's height, I mean the height of the track line, not the whole component height.

did you find any solution or fix?
I want to use the official library.

**Comment by luatnd** [comment] 2020-09-25 09:35
+1,
I tried all other libraries but this is only library that can work inside react-native-modal because of touch responder system.
At this time, we cannot modify track styles.
I haven't tried to set trackImage + thumb image yet

**Comment by Sharcoux** [comment] 2020-09-25 11:19
@luatnd So you tried @Sharcoux/slider and it doesn't work inside a react-native-modal, right? Do you want me to check if there is something I can do to fix this?

**Comment by luatnd** [comment] 2020-09-28 08:38
Glad to hear that @Sharcoux , it's all I want except working inside modal. I'm using `swipe down to dismiss` modal, the modal is taking higher touch priority.

**Comment by Sharcoux** [comment] 2020-09-28 09:45
Do you think that you could create a minimal sample code that reproduce the issue on any sandbox (codesandbox for instance)?

**Comment by scchess** [comment] 2020-12-25 11:38
Updates?

**Comment by AdrielHigor** [comment] 2021-04-22 20:47
updates?

**Comment by EnzoOctupus** [comment] 2021-06-30 17:31
No updates?

**Comment by renanbronchart** [comment] 2021-07-05 13:59
Updates or not?

**Comment by khmilevoi** [comment] 2021-08-05 08:58
No updates?

**Comment by Sharcoux** [comment] 2021-08-05 09:59
Guys, just use another lib. There are plenty out there, and this one is not more "official" than any other one, and it is less maintained. Move on.

**Comment by khmilevoi** [comment] 2021-08-05 15:33
> No updates?

I am using this library:  @miblanchard/react-native-slider

**Comment by Sharcoux** [comment] 2021-08-05 16:27
I use and maintain (@sharcoux/slider)[https://www.npmjs.com/package/@sharcoux/slider) with my company, but the lib from miblanchard seems good too depending on the use cases you have.

**Comment by BartoszKlonowski** [comment] 2023-01-18 14:33
Closing in favor of #40

**Closed by BartoszKlonowski** 2023-01-18 14:33 UTC
Labels: enhancement, question
