### ISSUE TITLE
The slider stopped working

### ISSUE THREAD

**Issue by valery-lavrik** [callstack/react-native-slider#416] opened 2022-08-11 10:48 UTC
Hello everyone
The slider has been working on the project for a long time, everything is fine with it.
But, today I tried to add to the project 
`yarn add valery-lavrik/react-native-fast-image`

how the app immediately stopped working.  The slider now throws an error:
![image](https://user-images.githubusercontent.com/8047999/184117163-bb7eab12-7c03-4a6f-8db8-92b317f0d1a4.png)

After I deleted valery-lavrik/react-native-fast-image, the slider didn't work anymore.   
 I tried:
`rm -rf node_modules`
`./gradlew clean`
`rm -rf android/.gradle`
restarting the computer

nothing helps.   
1) How to restore the application now
2) what exactly in the valery-lavrik/react-native-fast-image package broke the slider?

**Comment by BartoszKlonowski** [comment] 2022-08-11 11:12
Yes, this was introduced with the 4.3.0 version and it's a side effect of react-native-gradle-plugin fetched for Android.
We are currently working on it in #414.
However, I've tried to find the `valery-lavrik/react-native-fast-image` you mention, but I don't see it anywhere, so I can't even check which version is used in this package. Can you give me the direct link to it?

**Comment by valery-lavrik** [comment] 2022-08-11 11:16
@BartoszKlonowski   
https://github.com/valery-lavrik/react-native-fast-image

**Comment by BartoszKlonowski** [comment] 2022-08-11 11:36
@valery-lavrik I'm sorry, I thought you are using some external package, not yours internal one.
What I don't understand in the steps you provided is
> After I deleted valery-lavrik/react-native-fast-image, the slider didn't work anymore.

what exactly were the steps here?

**Comment by valery-lavrik** [comment] 2022-08-11 11:41
@BartoszKlonowski    
I found a solution:
`"@react-native-community/slider": "4.2.4",`
(removed the **^** symbol)

And it didn't work for me because after deleting the package I did **yarn**, which always puts the latest version (in the case of the browser - 4.3.0)
And I used to do **npm i** which installs packages a little differently

**Comment by BartoszKlonowski** [comment] 2022-08-12 21:51
@valery-lavrik OK, thank you!
I found a root cause and I'll work on the fix - as this issue is a duplicated item of #415 please track the progress there.
I will close this as a duplicate but I'll post here also when hotfix is released.

**Closed by BartoszKlonowski** 2022-08-12 21:51 UTC
Labels: bug report, duplicate, question

**Comment by BartoszKlonowski** [comment] 2022-08-20 11:49
@valery-lavrik  The fix is now released in v4.3.1
