### ISSUE TITLE
Error while updating property 'maximumValue' of a view managed by: RNCSlider when using calculated max etc.

### ISSUE THREAD

**Issue by wenxinzwang** [callstack/react-native-slider#498] opened 2023-03-03 14:49 UTC
## Environment

System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 15.40 GB / 31.88 GB
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.3 - D:\Git\EcoStream\mobile-app-src\node_modules\.bin\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 25, 26, 30, 31, 32, 33
      Build Tools: 25.0.3, 30.0.3, 31.0.0, 32.0.0, 33.0.0
      System Images: android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-32 | Google APIs Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
    Visual Studio: 17.4.33110.190 (Visual Studio Enterprise 2022)
  Languages:
    Java: 11.0.17 - C:\Program Files\Java\jdk-11.0.17\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Description

When calculate and set the properties (i.e., minimumValue, maximumValue, value, lowerLimit, and upperLimit) for several sliders, it gives error

> Error while updating property 'maximumValue' of a view managed by: RNCSlider
> null
> stack size 8MB

## Reproducible Demo

SliderComponent.js
```js

export default class SliderComponent extends Component {
//...
  slidingStart() {
    this.setState({ sliding: true });
  }

  valueChanged(value) {
    if (this.state.sliding) {
      this.setState({ shadowValue: value });
    }
  }

  valueConfirmed(value) {
    this.setState({ sliding: false });
    this.props.onConfirm(value);
  }

  render() {
    let step = 1;
    const { min, max, value, upperLimit, lowerLimit } = Helpers.calSliderLimits(this.props.value, this.props.lowerLimit, this.props.upperLimit, this.props.min, this.props.max);
    const showValue = this.state.sliding ? this.state.shadowValue : this.state.value;

    return (
      <View style={{ flex: 1, flexDirection: "row" }}>
        <View style={{ height: "100%", width: "83%" }}>
          <View style={{ flex: 1, alignItems: "center", flexDirection: "row" }}>
            <Slider
              style={[styles.sliderControl, this.props.styles]}
              value={this.state.value}
              minimumValue={this.state.min}
              lowerLimit={this.state.lowerLimit}
              upperLimit={this.state.upperLimit}
              maximumValue={this.state.max}
              step={step}
              thumbImage={this.state.thumbImage}
              minimumTrackTintColor={Colors.blue}
              thumbTintColor={Colors.blue}
              onSlidingStart={e => this.slidingStart()}
              onValueChange={e => this.valueChanged(e)}
              onSlidingComplete={e => this.valueConfirmed(e)}
            />
          </View>
        </View>
        <View style={[styles.sliderValueContainer]}>
          <Text style={[styles.sliderValueLabelLabel]}>
            {this.props.format != null ? this.props.format.replace("{0}", showValue) : showValue}
          </Text>
        </View>
      </View>
    );
  }
}
```

XxxScreen.js
```js
export class XxxScreen extends Component {
//...
_calFlowSliderSettings(minFlow, maxFlow, low, mid, high) {
    // First calculate max and min slider setting
    const flowMinSettings = Helpers.calSliderLimits(minFlow, null, maxFlow - 2, AppConfig.config_capacity_min, AppConfig.config_capacity_max);
    const flowMaxSettings = Helpers.calSliderLimits(maxFlow, flowMinSettings.value + 2, null, AppConfig.config_capacity_min, AppConfig.config_capacity_max);

    // Then calculate set point slider settings
    const pointHighSettings = Helpers.calSliderLimits(high, Math.max(mid + 1, flowMinSettings.value + 2), null, flowMinSettings.value, flowMaxSettings.value);
    const pointMidSettings = Helpers.calSliderLimits(mid, Math.max(low + 1, flowMinSettings.value + 1), pointHighSettings.value - 1, flowMinSettings.value, flowMaxSettings.value);
    const pointLowSettings = Helpers.calSliderLimits(low, null, pointMidSettings.value - 1, flowMinSettings.value, flowMaxSettings.value);
    return {
      flowMin: flowMinSettings,
      flowMax: flowMaxSettings,
      pointHigh: pointHighSettings,
      pointMid: pointMidSettings,
      pointLow: pointLowSettings,
    };
  }

  render() {
    const flowSliderSettings = this._calFlowSliderSettings(
      this.props.capacity_min,
      this.props.capacity_max,
      this.props.setpoint_low,
      this.props.setpoint_mid,
      this.props.setpoint_high);

return (
<View>
              <SliderComponent
                id="calibrationFlowMin"
                min={AppConfig.config_capacity_min}
                max={AppConfig.config_capacity_max}
                value={flowSliderSettings.flowMin.value}
                upperLimit={flowSliderSettings.flowMin.upperLimit}
                lowerLimit={flowSliderSettings.flowMin.lowerLimit}
                onConfirm={value => {
                  this._setFlow(value, Globals.calibrationType.min);
                }}
                format={i18n.t("calibrationFlowFormat")}
              />
              <SliderComponent
                id="calibrationFlowMax"
                min={AppConfig.config_capacity_min}
                max={AppConfig.config_capacity_max}
                value={flowSliderSettings.flowMax.value}
                upperLimit={flowSliderSettings.flowMax.upperLimit}
                lowerLimit={flowSliderSettings.flowMax.lowerLimit}
                onConfirm={value => {
                  this._setFlow(value, Globals.calibrationType.max);
                }}
                format={i18n.t("calibrationFlowFormat")}
              />

              <SliderComponent
                id="scheduleLevelIcon_high"
                min={flowSliderSettings.pointHigh.min}
                max={flowSliderSettings.pointHigh.max}
                value={flowSliderSettings.pointHigh.value}
                lowerLimit={flowSliderSettings.pointHigh.lowerLimit}
                upperLimit={flowSliderSettings.pointHigh.upperLimit}
                onConfirm={e => {
                  this._setVentilationLevelHigh(e);
                }}
                format={i18n.t("calibrationFlowFormat")}
              />
              <SliderComponent
                id="scheduleLevelIcon_mid"
                min={flowSliderSettings.pointMid.min}
                max={flowSliderSettings.pointMid.max}
                value={flowSliderSettings.pointMid.value}
                lowerLimit={flowSliderSettings.pointMid.lowerLimit}
                upperLimit={flowSliderSettings.pointMid.upperLimit}
                onConfirm={e => {
                  this._setVentilationLevelMid(e);
                }}
                format={i18n.t("calibrationFlowFormat")}
              />
              <SliderComponent
                id="scheduleLevelIcon_low"
                min={flowSliderSettings.pointLow.min}
                max={flowSliderSettings.pointLow.max}
                value={flowSliderSettings.pointLow.value}
                lowerLimit={flowSliderSettings.pointLow.lowerLimit}
                upperLimit={flowSliderSettings.pointLow.upperLimit}
                onConfirm={e => {
                  this._setVentilationLevelLow(e);
                }}
                format={i18n.t("calibrationFlowFormat")}
              /> 

              <SliderComponent
                min={0}
                max={100}
                value={this._getPercentageForVoltage(this.props.fan_balance_lut[Globals.calibrationType.min].eha)}
                onConfirm={percentageValue => {
                  this._setEhaInPercentage(percentageValue, Globals.calibrationType.min);
                }}
                format={i18n.t("calibrationPercentageFormat")}
              /> 
      </View>
    );
}
```

Helper function
```js
  /**
   * Calculate slider limits and value
   * @param {number} value the original value
   * @param {number} lowerLimit the original lower limit
   * @param {number} upperLimit the original upper limit
   * @param {number} min the original min
   * @param {number} max the original max
   * @returns 
   */
  calSliderLimits(value, lowerLimit, upperLimit, min, max) {
    // console.trace();
    // Set default values for min and max if they are not defined
    min = (min == null || isNaN(min)) ? 0 : min;
    max = (max == null || isNaN(max)) ? 100 : max;

    // Set default values for lowerLimit, upperLimit, min, and max if they are not defined
    lowerLimit = (lowerLimit == null || isNaN(lowerLimit)) ? min : lowerLimit;
    upperLimit = (upperLimit == null || isNaN(upperLimit)) ? max : upperLimit;

    // Make sure that the lower limit is within the bounds of min for lower and max for upper
    lowerLimit = Math.max(lowerLimit, min);
    lowerLimit = Math.min(lowerLimit, max);

    // Make sure that the upper limit is within the bounds of min for lower and max for upper
    upperLimit = Math.max(upperLimit, min);
    upperLimit = Math.min(upperLimit, max);

    // Make sure that the lower limit is below or equal to the upper limit
    lowerLimit = Math.min(lowerLimit, upperLimit);

    // Make sure that the upper limit is above or equal to the lower limit
    upperLimit = Math.max(upperLimit, lowerLimit);

    // Set default values for value, lowerLimit, upperLimit, min, and max if they are not defined
    value = (value == null || isNaN(value)) ? 0 : value;

    // Apply the lower and upper limits to the value
    value = Math.max(value, lowerLimit);
    value = Math.min(value, upperLimit);

    return {
      min: min,
      max: max,
      value: value,
      upperLimit: upperLimit,
      lowerLimit: lowerLimit
    };
  }
```

**Comment by BartoszKlonowski** [comment] 2023-03-03 15:51
Hello @wenxinzwang, thanks for taking the time to report the error.

Did you check in which exact Slider instantiation does the error happen? Could you debug a bit further to provide me with information on what exact value is passed to Slider for this failing `maximumValue`?
It would be awesome to have a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) so I can test it on my own as well.
Just to clarify: I'm always super happy to solve any problems developer have with the library, but sometimes I could also use a bit of help as well.

**Comment by BartoszKlonowski** [comment] 2023-04-11 10:23
Closing due to lack of authors interest and lack of possible bug reproduction.

**Closed by BartoszKlonowski** 2023-04-11 10:23 UTC
Labels: bug report, platform: Android, requires: author feedback
