### ISSUE TITLE
Discrete Values

### ISSUE THREAD

**Issue by gkupsaw** [callstack/react-native-slider#218] opened 2020-08-19 04:48 UTC
## Describe the Feature
I'm not sure if this is already exists, but it would be nice to have the option to use discrete values for the slider instead of continuous options.

## Possible Implementations
It would probably be easiest to emulate the code of existing discrete slider implementations on the web. I haven't thought too deeply about the implementation yet, but would gladly look into it if it's something to be added.

## Related Issues
An example of this kind of slider: https://material-ui.com/components/slider/#discrete-sliders
(Unmanaged) implementation in RN: https://www.npmjs.com/package/react-native-snap-slider

**Comment by smallsaucepan** [comment] 2020-09-25 09:34
Possibly a duplicate of #71 ?

**Comment by BartoszKlonowski** [comment] 2021-08-22 13:29
This is a duplicate of #71 as already mentioned by @smallsaucepan.
I will close this and move examples given by @gkupsaw to the origin issue.
Please track the progress there.

**Closed by BartoszKlonowski** 2021-08-22 13:29 UTC
Labels: duplicate, feature request
