### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by mezalejandro** [callstack/react-native-slider#193] opened 2020-06-17 10:47 UTC
## Environment

System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 19.48 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    npm: 6.14.5 - /Volumes/MacintoshHD/work/apps/myapp/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.1, 29.0.2, 29.0.3, 30.0.0
      System Images: android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
## Description

Hello in Crashlytics I have the error:

Fatal Exception: java.lang.NullPointerException: Attempt to write to field 'java.util.ArrayList android.animation.AnimatorSet$Node.nodeDependents' on a null object reference
       at android.animation.AnimatorSet.clone(AnimatorSet.java:700)
       at android.animation.AnimatorSet.clone(AnimatorSet.java:51)
       at android.animation.Animator$AnimatorConstantState.newInstance(Animator.java:562)
       at android.animation.Animator$AnimatorConstantState.newInstance(Animator.java:543)
       at android.content.res.ConstantState.newInstance(ConstantState.java:50)
       at android.content.res.ConstantState.newInstance(ConstantState.java:58)
       at android.content.res.ConfigurationBoundResourceCache.getInstance(ConfigurationBoundResourceCache.java:48)
       at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:113)
       at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState$PendingAnimator.newInstance(AnimatedVectorDrawable.java:567)
       at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState.inflatePendingAnimators(AnimatedVectorDrawable.java:545)
       at android.graphics.drawable.AnimatedVectorDrawable.applyTheme(AnimatedVectorDrawable.java:377)
       at android.graphics.drawable.DrawableContainer$DrawableContainerState.applyTheme(DrawableContainer.java:865)
       at android.graphics.drawable.DrawableContainer.applyTheme(DrawableContainer.java:577)
       at android.graphics.drawable.StateListDrawable.applyTheme(StateListDrawable.java:370)
       at android.graphics.drawable.AnimatedStateListDrawable.applyTheme(AnimatedStateListDrawable.java:391)
       at android.content.res.Resources.loadDrawable(Resources.java:2695)
       at android.content.res.HwResources.loadDrawable(HwResources.java:732)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:912)
       at android.widget.AbsSeekBar.<init>(AbsSeekBar.java:96)
       at android.widget.SeekBar.<init>(SeekBar.java:85)
       at android.widget.SeekBar.<init>(SeekBar.java:81)
       at androidx.appcompat.widget.AppCompatSeekBar.<init>(AppCompatSeekBar.java:47)
       at com.reactnativecommunity.slider.ReactSlider.<init>(ReactSlider.java:64)
       at com.reactnativecommunity.slider.ReactSliderManager$ReactSliderShadowNode.measure(ReactSliderManager.java:68)
       at com.facebook.yoga.YogaNodeJNIBase.measure(YogaNodeJNIBase.java:474)
       at com.facebook.yoga.YogaNative.jni_YGNodeCalculateLayout(YogaNative.java)
       at com.facebook.yoga.YogaNodeJNIBase.calculateLayout(YogaNodeJNIBase.java:182)
       at com.facebook.react.uimanager.ReactShadowNodeImpl.calculateLayout(ReactShadowNodeImpl.java:463)
       at com.facebook.react.uimanager.UIImplementation.calculateRootLayout(UIImplementation.java:883)
       at com.facebook.react.uimanager.UIImplementation.updateViewHierarchy(UIImplementation.java:638)
       at com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates(UIImplementation.java:599)
       at com.facebook.react.uimanager.UIManagerModule.onBatchComplete(UIManagerModule.java:782)
       at com.facebook.react.bridge.NativeModuleRegistry.onBatchComplete(NativeModuleRegistry.java:118)
       at com.facebook.react.bridge.CatalystInstanceImpl$BridgeCallback.onBatchComplete(CatalystInstanceImpl.java:164)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
       at android.os.Looper.loop(Looper.java:150)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
       at java.lang.Thread.run(Thread.java:833)

My code:
`<Slider
                        style={{width: '60%',}}
                        minimumValue={0}
                        value={this.state.currentTime}
                        maximumValue={this.state.duration}
                        minimumTrackTintColor={Colors.secondary}
                        maximumTrackTintColor={'#ccc'}                    
                        onSlidingComplete={data => this.seekTo(data)}
                        onSlidingStart={data => this.setState({paused: true})}
                        thumbTintColor={'#fff'}
                      />`

**Comment by BartoszKlonowski** [comment] 2021-08-21 19:17
Hello @mezalejandro! I can see that this issue has been reported on an outdated version of this library and RN.
I've double checked whether the same error happens on the latest release (*v4.1.1*),
can you check on your side?

**Comment by mezalejandro** [comment] 2021-08-23 12:43
Thanks @BartoszKlonowski , I'm going to try it again,

**Comment by BartoszKlonowski** [comment] 2021-08-29 01:15
@mezalejandro I've kept the `requires: author feedback` label. Can you let me know if the issue still occurs on the latest as soon as you check it, please?

**Comment by BartoszKlonowski** [comment] 2021-09-07 13:17
Hello @mezalejandro!
I will close this issue as I assume that the problem is solved with the latest version.
Let me know if you disagree.

**Closed by BartoszKlonowski** 2021-09-07 13:17 UTC
Labels: bug report, platform: Android, requires: author feedback

**Comment by BennyTian** [comment] 2022-02-15 05:22
the same problem.

env:
"@react-native-community/slider": "^4.2.0",
"react-native": "0.61.5",

device:
android 4.3 / 4.2.2


another bug:

`tried to access method android.widget.SeekBar.isAccessibilityFocused:(Lcom/reactnativecommunity/slider/ReactSlider;D)V from class com.reactnativecommunity.slider.ReactSliderManager
com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:98)`
