### ISSUE TITLE
Execution failed for task ':react-native-community_slider:compileDebugJavaWithJavac'. | New architecture

### ISSUE THREAD

**Issue by AdhamMahmoud98** [callstack/react-native-slider#452] opened 2022-11-02 13:25 UTC
I am trying to build a react native app using the new architecture with react-native version 0.70.3, and I set newArchEnabled in Gradle.properties.

The error I am getting when the build fails is Execution failed for task ':react-native-community_slider:compileDebugJavaWithJavac'. and the logs show multiple lines of the issue listed below:
/node_modules/@react-native-community/slider/android/src/newarch/java/com/reactnativecommunity/slider/ReactSliderManager.java:183: error: method does not override or implement a method from a supertype
  @Override

**Comment by BartoszKlonowski** [comment] 2022-11-03 00:52
Hello @AdhamMahmoud98!
I was unable to reproduce the issue you posted here, so maybe you could provide me with the link to some reproduction repo of yours so I can clone and investigate?
In the meantime: Could you clone and run the [example app](https://github.com/callstack/react-native-slider/tree/main/example) of this project? I just tested it and it builds fine (it's not far behind yours regarding React Native versions) so maybe you can use that as a comparison or check against some local issues?

**Comment by CaptainJeff** [comment] 2022-11-03 16:46
Same issue!

**Comment by BartoszKlonowski** [comment] 2022-11-06 16:28
@CaptainJeff Did you run the full clean of Android build directory before building for new architecture?

**Comment by snowiosic** [comment] 2022-11-16 08:09
same issue

**Comment by HeatherHaylett** [comment] 2022-11-21 22:28
I've run into this issue as well. Error log:

```
/Users/heatherhaylett/vouch/vk-auto-app/node_modules/@react-native-community/slider/android/src/main/java/com/reactnativecommunity/slider/ReactSliderEvent.java:18: error: ReactSliderEvent is not abstract and does not override abstract method dispatch(RCTEventEmitter) in Event
public class ReactSliderEvent extends Event<ReactSliderEvent> {
       ^
/Users/heatherhaylett/vouch/vk-auto-app/node_modules/@react-native-community/slider/android/src/main/java/com/reactnativecommunity/slider/ReactSliderEvent.java:51: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/heatherhaylett/vouch/vk-auto-app/node_modules/@react-native-community/slider/android/src/main/java/com/reactnativecommunity/slider/ReactSlidingCompleteEvent.java:18: error: ReactSlidingCompleteEvent is not abstract and does not override abstract method dispatch(RCTEventEmitter) in Event
public class ReactSlidingCompleteEvent extends Event<ReactSlidingCompleteEvent> {
       ^
/Users/heatherhaylett/vouch/vk-auto-app/node_modules/@react-native-community/slider/android/src/main/java/com/reactnativecommunity/slider/ReactSlidingCompleteEvent.java:49: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/heatherhaylett/vouch/vk-auto-app/node_modules/@react-native-community/slider/android/src/main/java/com/reactnativecommunity/slider/ReactSlidingStartEvent.java:19: error: ReactSlidingStartEvent is not abstract and does not override abstract method dispatch(RCTEventEmitter) in Event
public class ReactSlidingStartEvent extends Event<ReactSlidingStartEvent> {
       ^
/Users/heatherhaylett/vouch/vk-auto-app/node_modules/@react-native-community/slider/android/src/main/java/com/reactnativecommunity/slider/ReactSlidingStartEvent.java:49: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: /Users/heatherhaylett/vouch/vk-auto-app/node_modules/@react-native-community/slider/android/src/main/java/com/reactnativecommunity/slider/ReactSliderManagerImpl.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/heatherhaylett/vouch/vk-auto-app/node_modules/@react-native-community/slider/android/src/oldarch/java/com/reactnativecommunity/slider/ReactSliderManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
6 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-community_slider:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by Jay-CTSH** [comment] 2022-12-19 07:20
> I am trying to build a react native app using the new architecture with react-native version 0.70.3, and I set newArchEnabled in Gradle.properties.
> 
> The error I am getting when the build fails is Execution failed for task ':react-native-community_slider:compileDebugJavaWithJavac'. and the logs show multiple lines of the issue listed below: /node_modules/@react-native-community/slider/android/src/newarch/java/com/reactnativecommunity/slider/ReactSliderManager.java:183: error: method does not override or implement a method from a supertype @OverRide

I was getting this same issue, but what worked for me was updating the android studio emulator SDK. Follow these steps:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"

**Comment by ogizanagi** [comment] 2022-12-30 10:10
We get the [same issue](https://github.com/callstack/react-native-slider/issues/452#issuecomment-1322734891) with React Native 0.64 and slider v4.4.0.

Can this package actually be used [>=4.3.0](https://github.com/callstack/react-native-slider/releases/tag/v4.3.0) without switching to the new architecture (introduced in react-native 0.68), with react-native 0.64 ? Or should we downgrade to v4.2.x ?

**Comment by Hzyhhh** [comment] 2023-01-04 03:24
```
"react": "16.13.1",
"react-native": "0.63.4",
```
![image](https://user-images.githubusercontent.com/25975853/210478335-ec1c57f7-3a0b-4e10-9001-995dad194535.png)

**try downgrade version to 3.0.x**
```shell
yarn add @react-native-community/slider@3.x
```
it work for me

**Comment by Malik-Usman17** [comment] 2023-03-08 13:41
> I've run into this issue as well. Error log:
> 
> ```
> /Users/heatherhaylett/vouch/vk-auto-app/node_modules/@react-native-community/slider/android/src/main/java/com/reactnativecommunity/slider/ReactSliderEvent.java:18: error: ReactSliderEvent is not abstract and does not override abstract method dispatch(RCTEventEmitter) in Event
> public class ReactSliderEvent extends Event<ReactSliderEvent> {
>        ^
> /Users/heatherhaylett/vouch/vk-auto-app/node_modules/@react-native-community/slider/android/src/main/java/com/reactnativecommunity/slider/ReactSliderEvent.java:51: error: method does not override or implement a method from a supertype
>   @Override
>   ^
> /Users/heatherhaylett/vouch/vk-auto-app/node_modules/@react-native-community/slider/android/src/main/java/com/reactnativecommunity/slider/ReactSlidingCompleteEvent.java:18: error: ReactSlidingCompleteEvent is not abstract and does not override abstract method dispatch(RCTEventEmitter) in Event
> public class ReactSlidingCompleteEvent extends Event<ReactSlidingCompleteEvent> {
>        ^
> /Users/heatherhaylett/vouch/vk-auto-app/node_modules/@react-native-community/slider/android/src/main/java/com/reactnativecommunity/slider/ReactSlidingCompleteEvent.java:49: error: method does not override or implement a method from a supertype
>     @Override
>     ^
> /Users/heatherhaylett/vouch/vk-auto-app/node_modules/@react-native-community/slider/android/src/main/java/com/reactnativecommunity/slider/ReactSlidingStartEvent.java:19: error: ReactSlidingStartEvent is not abstract and does not override abstract method dispatch(RCTEventEmitter) in Event
> public class ReactSlidingStartEvent extends Event<ReactSlidingStartEvent> {
>        ^
> /Users/heatherhaylett/vouch/vk-auto-app/node_modules/@react-native-community/slider/android/src/main/java/com/reactnativecommunity/slider/ReactSlidingStartEvent.java:49: error: method does not override or implement a method from a supertype
>     @Override
>     ^
> Note: /Users/heatherhaylett/vouch/vk-auto-app/node_modules/@react-native-community/slider/android/src/main/java/com/reactnativecommunity/slider/ReactSliderManagerImpl.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: /Users/heatherhaylett/vouch/vk-auto-app/node_modules/@react-native-community/slider/android/src/oldarch/java/com/reactnativecommunity/slider/ReactSliderManager.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 6 errors
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-community_slider:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> ```
> 
> My project uses: `"@react-native-community/slider": "^4.3.3"` `"react-native": "0.63.5"`
> 
> ```
> buildscript {
>     ext {
>         buildToolsVersion = "29.0.3"
>         minSdkVersion = 24
>         compileSdkVersion = 31
>         targetSdkVersion = 31
>     }
> ```

same issue facing?anyone can help

**Comment by megabeehothanhminh** [comment] 2023-06-02 05:24
[Malik-Usman17](https://github.com/Malik-Usman17)

I changed to "@react-native-community/slider": "4.1.12"
Working good

**Comment by Malik-Usman17** [comment] 2023-06-02 06:37
> [Malik-Usman17](https://github.com/Malik-Usman17)
> 
> I changed to "@react-native-community/slider": "4.1.12" Working good

Yeah that also worked for me, thanks

**Comment by BartoszKlonowski** [comment] 2023-07-07 11:54
The closing PR was not properly linked, however please note the changes in the compatibility table in the README for more info.
Sorry for any inconveniences!

**Closed by BartoszKlonowski** 2023-07-07 11:54 UTC
Labels: bug report, platform: Android, new architecture
