### ISSUE TITLE
requirenativecomponent:"RNSlider" was not found

### ISSUE THREAD

**Issue by jetBn** [callstack/react-native-slider#189] opened 2020-06-09 04:05 UTC
why I use show this?

**Comment by leup** [comment] 2020-06-13 16:13
May be related to this ? 

https://github.com/react-native-community/react-native-slider/issues/152

Have you tried to search in the issues ?

**Comment by BartoszKlonowski** [comment] 2021-08-20 22:21
@jetBn Can you provide more information?
What is the platform?
What version do you use?
Is the issue still valid if you try it with the latest release?
What are the reproduction steps?

**Comment by BartoszKlonowski** [comment] 2021-09-01 10:52
Closing due to lack of author's feedback.

**Closed by BartoszKlonowski** 2021-09-01 10:52 UTC
Labels: bug report, requires: author feedback
