### ISSUE TITLE
Image not rendering on slider

### ISSUE THREAD

**Issue by nakshatrasinghh** [callstack/react-native-slider#478] opened 2023-01-09 08:28 UTC
## Ask your Question

Why does the image prop not work?

**Comment by BartoszKlonowski** [comment] 2023-01-09 09:30
Hello @nakshatrasinghh! Is there any specific platform you observe this issue on?

**Comment by nakshatrasinghh** [comment] 2023-01-10 03:37
Hello @BartoszKlonowski, yes this issue is on web and mobile phone both

**Comment by nakshatrasinghh** [comment] 2023-01-11 05:32
Any update @BartoszKlonowski

**Comment by nakshatrasinghh** [comment] 2023-01-13 09:58
Any update @BartoszKlonowski?

**Comment by BartoszKlonowski** [comment] 2023-01-13 11:10
> Any update @BartoszKlonowski?

I believe this is a duplicate of #346 when it comes to mobile platform.
But when it comes to Web implementation - I'll be happy to see your repro example and more details of this issue (versions you're using, scenario, etc).

**Closed** 2023-01-14 09:31 UTC
Labels: bug report
