### ISSUE TITLE
Disabled Prop not working in Web when used with react-native-web

### ISSUE THREAD

**Issue by hpurohit97** [callstack/react-native-slider#261] opened 2021-01-28 09:03 UTC

**Comment by Sharcoux** [comment] 2021-02-01 15:09
Can you check if you can reproduce with the last version of @sharcoux/slider (`npm i @sharcoux/slider`)

**Comment by BartoszKlonowski** [comment] 2021-09-15 08:25
Hello @hpurohit97!
Could you provide this issue with some reproduction example and the environment's information?

**Comment by BartoszKlonowski** [comment] 2021-09-29 15:23
Closing due to no feedback from an author.

**Closed by BartoszKlonowski** 2021-09-29 15:23 UTC
Labels: bug report, requires: author feedback
