### ISSUE TITLE
Extra padding on android and ios ,

### ISSUE THREAD

**Issue by HITESH122** [callstack/react-native-slider#258] opened 2021-01-19 08:19 UTC
## Environment

System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 57.86 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.2.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 30
      Build Tools: 28.0.3, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.9.0 => 16.9.0 
    react-native: ^0.63.2 => 0.63.4 
    react-native-macos: N

**Comment by HITESH122** [comment] 2021-01-19 12:46
![Screenshot 2021-01-19 at 12 46 56 PM](https://user-images.githubusercontent.com/25567410/105036340-5c8e2580-5a82-11eb-9d23-ba6244dcd016.png)

**Comment by wojteg1337** [comment] 2021-01-28 12:15
@HITESH122 Could you provide more context?

**Comment by Daniel-Alencar** [comment] 2021-02-01 17:17
My app is also like this. Although I have not tested on IOS.

**Comment by HITESH122** [comment] 2021-02-02 06:06
> @HITESH122 Could you provide more context?

@wojteg1337 I need to plot markers according to percentage but slider thumb is not starting from extreme left for ios its taking the slight padding

**Comment by pstevovski** [comment] 2021-02-02 23:56
Same thing is happening on Android emulator (and I suppose the same on physical device). Can't get it to be the exact full width of the container, has some padding I suppose.

![image](https://user-images.githubusercontent.com/36767249/106678202-85520700-65ba-11eb-946f-3682367029d0.png)

**Comment by HITESH122** [comment] 2021-02-06 05:50
> Same thing is happening on Android emulator (and I suppose the same on physical device). Can't get it to be the exact full width of the container, has some padding, though I looked in the `src/js/Slider.js` and couldn't find anything that would cause it to have paddings?
> 
> ![image](https://user-images.githubusercontent.com/36767249/106678202-85520700-65ba-11eb-946f-3682367029d0.png)

Hello @pstevovski  use this pr for android fix 
https://github.com/callstack/react-native-slider/pull/170

For ios We need to get some solution

**Comment by viveKing21** [comment] 2021-06-29 15:12
> > Same thing is happening on Android emulator (and I suppose the same on physical device). Can't get it to be the exact full width of the container, has some padding, though I looked in the `src/js/Slider.js` and couldn't find anything that would cause it to have paddings?
> > ![image](https://user-images.githubusercontent.com/36767249/106678202-85520700-65ba-11eb-946f-3682367029d0.png)
> 
> Hello @pstevovski use this pr for android fix
> #170
> 
> For ios We need to get some solution

Still not working on android

**Comment by kolyuchii** [comment] 2021-07-09 19:39
Same issue for me on android

**Comment by ratz6** [comment] 2022-02-22 02:49
Facing same issue on android. And giving padding in styles isn't helping

**Comment by Dajust** [comment] 2022-05-26 23:48
16 months later...

**Comment by tastafur** [comment] 2022-12-29 12:14
@BartoszKlonowski It would be nice if we could fix the padding issue

**Comment by BartoszKlonowski** [comment] 2023-01-19 14:46
This issue is a duplicate of #98. Please track the progress in original issue.

**Closed by BartoszKlonowski** 2023-01-19 14:46 UTC
Labels: bug report, duplicate, platform: Android, platform: iOS
