### ISSUE TITLE
Add cacheTintColor and cacheValue for youtube slider like caching

### ISSUE THREAD

**Issue by KKKaisar** [callstack/react-native-slider#622] opened 2024-08-22 08:01 UTC
## Describe the Feature

There is maximumTrackTint with minimumTrackTint which works perfect. But there is no cacheTint which will show us loaded cache of video or audio. Please add it. You can see how it should look on gif in https://github.com/alantoa/react-native-awesome-slider/tree/main
## Possible Implementations

showCache boolean to show it. It should be in space between thumbTint and the end of slider. Should have cacheValue, should be in range between minimumValueand maximumValueslider value, if it is hard then another way between value and maximumValue. Should have cacheTintColor to see it different than maximumTrackTint Color.

**Comment by BartoszKlonowski** [comment] 2024-09-11 19:38
Hello @KKKaisar!
I believe this is a duplicate of #602, so let me close this one.
If you would like to speed things up you can check out the PR already made for Android platform or deep dive into how to achieve this on iOS. Any support is most welcome!
Thank you for your patience.

**Closed by BartoszKlonowski** 2024-09-11 19:38 UTC
Labels: duplicate, feature request
