### ISSUE TITLE
Multiple Knobs Slider

### ISSUE THREAD

**Issue by ralph-dev** [callstack/react-native-slider#228] opened 2020-09-21 22:45 UTC
## Describe the Feature
The ability for a Slider to Feature Multiple Knobs in order to handle Bounded Ranges (Ex: Values in-between X and Y).

## Possible Implementations
I've attached a screenshot of what I've built in isolation, hoping someone can duplicate this but into the library?

![image](https://user-images.githubusercontent.com/7469722/93829013-72e5bb00-fc21-11ea-9e44-fcdd613b9ca4.png)

This is currently working but I would love to delete this and just use this library instead for joint maintainability reasons :)

**Comment by KyleAsaff** [comment] 2021-01-03 20:39
@ralph-dev could you share your implementation, I really need this feature 😅

**Comment by Sharcoux** [comment] 2021-02-01 15:23
@ralph-dev Try @sharcoux/slider it supports range-slider. I'm opening a discussion to try and make it the "official" implementation for React Native as the current one is really poor in terms of support and features

**Comment by ralph-dev** [comment] 2021-02-01 15:48
> @ralph-dev Try @sharcoux/slider it supports range-slider. I'm opening a discussion to try and make it the "official" implementation for React Native as the current one is really poor in terms of support and features

I'd also be happy to contribute the code above as well!

**Comment by Sharcoux** [comment] 2021-02-01 16:32
@ralph-dev My bad, I was targetting @KyleAsaff :sweat_smile:

**Comment by KyleAsaff** [comment] 2021-02-01 20:25
@Sharcoux and @ralph-dev I'm currently using https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider but I would love to use this library instead

**Comment by fbartho** [comment] 2021-02-18 18:17
We also would appreciate this, rather than pulling in a new dependency!

**Comment by Sharcoux** [comment] 2021-02-18 18:50
@fbartho react-native-slider is already a new dependency. They are supposed to move away from react-native-community. See  [this](https://github.com/react-native-community/discussions-and-proposals/issues/330) for more details. In the end, there is no difference between one dependency and the other.

**Comment by fbartho** [comment] 2021-02-18 20:16
@Sharcoux -- Sorry, I must have been unclear, I meant that my team is already using react-native-slider, but now we also need a slider with multiple drag handles. I'd rather not have to migrate entirely to react-native-multi-slider, and also not have to include 2 slider libraries.

**Comment by Sharcoux** [comment] 2021-02-18 21:13
@fbartho The slider I mentioned can handle both (simple slider and range slider) and is following the same API except that it has more features. You might want to change to only this one, but that's up to you.

**Comment by BartoszKlonowski** [comment] 2021-06-28 10:34
I can see that this is a duplicate of #25 
@ralph-dev Thank you for your report!
I'm going to close this one and mark it as a duplicate, so all the work on this enhancement can be tracked from the original issue.

FYI @michalchudziak

**Closed by BartoszKlonowski** 2021-06-28 10:34 UTC
Labels: duplicate, feature request
