### ISSUE TITLE
RTL issues in Android and iPhone

### ISSUE THREAD

**Issue by danielbenedykt** [callstack/react-native-slider#272] opened 2021-03-19 11:54 UTC
## Environment

react: 16.13.1 => 16.13.1 
react-native: ~0.63.3 => 0.63.3 

## Description
When using/forcing RTL there are issues on the sliders

I use :  I18nManager.forceRTL(true);

**Android:**
Set   invert_slider = true   to make it look correct in all phones (English phones for example)
_Issue_:  When the language of the phone is in hebrew,  the slider always shows in the wrong way.  (invert_slider does not have any effect)

**iPhone:**
Set   invert_slider = false  ,  because it seems that the forceRTL automatically flips the values
_Issue_:  the fill color (black vs white) its on the wrong side

## Reproducible Demo

<Slider
                  inverted={this.invert_slider}
                  style={{flex:1, height: 40}}
                  minimumValue={5}
                  maximumValue={25}
                  step={5}
                  minimumTrackTintColor="#DDDDDD"
                  maximumTrackTintColor="#000000"
                  thumbTintColor="#788eec"
                  value={this.props.thevalue}
                  onSlidingComplete={value => this.onSlidingComplete(value)}
                />

**Comment by mosoakinyemi** [comment] 2021-03-29 16:25
Hi @danielbenedykt 👋🏼,
Kindly review this demo on Expo https://snack.expo.io/@mishael_akinyemi/rtl-issue and see if you could reproduce your issue.

**Comment by BartoszKlonowski** [comment] 2021-09-15 13:01
Hello @danielbenedykt!
I can see that this issue has been reported on a previous versions of react native and Slider packages.
Can you verify if the issue still exists on the latest versions?
Could you also check the demo provided by @mosoakinyemi?

**Comment by BartoszKlonowski** [comment] 2021-09-29 15:23
Closing due to no feedback from an author.

**Closed by BartoszKlonowski** 2021-09-29 15:23 UTC
Labels: bug report, requires: author feedback

**Comment by BartoszKlonowski** [comment] 2021-09-29 15:28
@mosoakinyemi Of course feel free to reopen if you still would like to work on this item,
