### ISSUE TITLE
Slider doesn't work (with Expo) on Android 13

### ISSUE THREAD

**Issue by VeroLeia** [callstack/react-native-slider#474] opened 2023-01-03 11:21 UTC
Confirmed on two separate devices, one of which it worked on before upgrading to 13.

Error: requireNativeComponent: "RNCSlider" was not found in the UIManager

**Comment by BartoszKlonowski** [comment] 2023-01-04 11:06
This is most likely a duplicate of #330  which has recently been reported as occuring on Android devices as well.
Closing as a duplicate.

**Closed by BartoszKlonowski** 2023-01-04 11:06 UTC
Labels: bug report, duplicate, platform: Android
